//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextDeleteLabel {
            get {
                return ResourceManager.GetString("ContextDeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authored By に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderAuthoredBy {
            get {
                return ResourceManager.GetString("DataGridHeaderAuthoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderDate {
            get {
                return ResourceManager.GetString("DataGridHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderDocumentType {
            get {
                return ResourceManager.GetString("DataGridHeaderDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderFormat {
            get {
                return ResourceManager.GetString("DataGridHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderTemplateName {
            get {
                return ResourceManager.GetString("DataGridHeaderTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportButtonLabel {
            get {
                return ResourceManager.GetString("ExportButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadButtonLabel {
            get {
                return ResourceManager.GetString("LoadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MutexMesseage {
            get {
                return ResourceManager.GetString("MutexMesseage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open temp. folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenTempButtonLabel {
            get {
                return ResourceManager.GetString("OpenTempButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patient Id: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatientIdLabel {
            get {
                return ResourceManager.GetString("PatientIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patient Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatientNameLabel {
            get {
                return ResourceManager.GetString("PatientNameLabel", resourceCulture);
            }
        }
    }
}
